### Your details

Name: **Siddharth Prince**

ID number: **23052058**

# Task 1

## Approach

(Describe the approaches you took, etc.)

## Manual Calculations

(If you used manual calculations to verify your code, mention them here)

## Code

### House keeping code which includes any imports, general variable declarations, etc

In [5]:
# Imports
import numpy as np
from typing import List

### Note

The first code cell below contains all class code and util functions that would be useful in the context of a vector object. All the functions that implement the solutions to the given problems shall be provided in their own cells after the below code cell. This is my attempt at presenting my code in more readable chunks instead of a single class block with all the code in it.

### a. Vectors

In [88]:
# Defining a vector class so that it becomes more intuitive and straightforward to use these as objects and reduce code repetition.
# Working with Java for 3 years in industry has changed me as a programmer. :)
class Vector:
    # Initialising a Vector object with a list of numbers provided.
    def __init__(self, v: List):
        self.v = v
        self.len = len(v)

    # Defining the string representation of the object for print(). 
    # I did notice that numpy prints all elements without the comma, but that just seems cosmetic here.
    def __str__(self):
        return str(self.v)

    # Util function to set all values of the vector.
    def setVector(self, v: List):
        self.v = v
        

In [89]:
# Util function that checks if the passed Vector object has the same length as the current Vector object.
def checkIfEqualSize(self, v: Vector):
    return self.len == v.len

# adding above util function to the Vector class. 
# Had to add this in a separate code cell as I needed to check the passed parameter by type Vector.
Vector.checkIfEqualSize = checkIfEqualSize

### Task 1.a.i Scalar multiplication of vectors  
Scalar multiplication or "scaling" a vector as intuitively explained by 3B1B, is multiplying all components of a vector (usually the x, y and z components which represents it in 3d space) by a constant factor.  

In my below implementation of the function to scale a vector, I have added the function "scaleVector" to the Vector class. The only parameter that is required is the scalar value. This function multiplies the vector object in place and prints the new vector object.

In [90]:
# Function to scale a vector. This function changes the vector values in place.
def scaleVector(self, scalar: float):
    self.v = [scalar*i for i in self.v]
    print(f"New scaled vector: {self.v}")

# adding the above function to the Vector class
Vector.scale = scaleVector

In [91]:
# Test cases
v1 = Vector([1,2,3])
print('Scaling v1 by a factor of 2:')
v1.scale(2)
print('Scaling v1 by a factor of -0.5:')
v1.scale(-0.5)
print('Setting new values to v1:')
v1.setVector([1,2,3]) # testing the setVector util function where it will change an existing vector to the new values provided
v2 = Vector([14012, -52, 332.1])
print('Scaling v2 by a factor of 2:')
v2.scale(2)
# v3 = Vector([1])
# v3.scale(69)

Scaling v1 by a factor of 2:
New scaled vector: [2, 4, 6]
Scaling v1 by a factor of -0.5:
New scaled vector: [-1.0, -2.0, -3.0]
Setting new values to v1:
Scaling v2 by a factor of 2:
New scaled vector: [28024, -104, 664.2]


**Verifying the above cases with Numpy**

In [92]:
# Verifying with Numpy

n1 = np.array([1,2,3])
print('Scaling n1 by a factor of 2:')
n2 = 2*n1
print(n2)
print('Scaling n1 by a factor of -0.5:')
print(-0.5*n2)

Scaling n1 by a factor of 2:
[2 4 6]
Scaling n1 by a factor of -0.5:
[-1. -2. -3.]


### Task 1.a.ii Addition and subtraction of vectors



In [93]:
# Function for vector addition. This does not perform addition in place to the vector object.
def add(self, vector: Vector) -> Vector:
    if self.checkIfEqualSize(vector):
        return Vector([self.v[i] + vector.v[i] for i in range(self.len)])
    else:
        raise Exception(f'Vector of length {self.len} required to perform vector addition. Provided vector is of length {vector.len}')
        

# Function for vector addition. This does not perform addition in place to the vector object.
def subtract(self, vector: Vector) -> Vector:
    if self.checkIfEqualSize(vector):
        return Vector([self.v[i] - vector.v[i] for i in range(self.len)])
    else:
        raise Exception(f'Vector of length {self.len} required to perform vector subtraction. Provided vector is of length {vector.len}')

# adding the above functions to the Vector class
Vector.add = add
Vector.subtract = subtract

In [167]:
# Sum of vectors
print("Sum of vectors")
# Test cases
print(f'Vector v1: {v1}')
v2.setVector([10, 20, 30])
print(f'Vector v2: {v2}')
v3 = v1.add(v2)
print('Adding v1 & v2:')
print(v3)
print()
v1.setVector([-1, -2, -3])
print()
print(v1.add(v2))

# Subtraction of vectors
print("\nSubtraction of vectors")
# Test cases
v4 = v1.subtract(v2)
print(v4)
print()
v5 = v3.subtract(v2)
print(v5)

# Testing for Vectors with unequal lengths. The following cases should fail with an exception and appropriate message.
v6 = Vector([1,2,3,4])
# v5.add(v6) # Passed
v5.subtract(v6) # Passed

Sum of vectors
Vector v1: [-1, -2, -3]
Vector v2: [10, 20, 30]
Adding v1 & v2:
[9, 18, 27]


[9, 18, 27]

Subtraction of vectors
[-11, -22, -33]

[-1, -2, -3]


Exception: Vector of length 3 required to perform vector subtraction. Provided vector is of length 4

**Verifying the above cases with Numpy**

In [95]:
n2 = np.array([10,20,30])
print(n1 + n2)
print(n1 - n2)
n3 = np.array([1,2,3,4])
# n1 + n3 # testing for vector arithmetic operations of unequal size
n3 - n1 # Throws a more generic error message which has its merits for only having to maintain a single method, but... Sid's implementation - 1, Numpy - 0 XD

[11 22 33]
[ -9 -18 -27]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### Task 1.a.iii Dot product of vectors  
Dot product of vectors, from my understanding, is the sum of all corresponding products of elements of two equal length vectors. The below 'dot' method takes one argument of type Vector and returns the scalar dot product value of the Vector object of whose dot method is called and the Vector object which is passed to the dot method. Refer the test case cell for examples.

In [96]:
# Function to compute the dot product of two vectors.
def dot(self, vector: Vector) -> int:
    # Checking that both Vector objects are of the same length.
    if self.checkIfEqualSize(vector):
        dotProduct = 0
        productList = [self.v[i] * vector.v[i] for i in range(self.len)]
        for number in productList:
            dotProduct += number
        return dotProduct
    else:
        raise Exception(f'Vector of length {self.len} required to obtain the dot product. Provided vector is of length {vector.len}')

# Adding the dot function to the Vector class
Vector.dot = dot

In [97]:
# Test cases
print(v5)
print(v2)
print(v5.dot(v2))
print(v2.dot(v5))

# Testing with a vector having negative elements in it
print(v1)
print(v1.dot(v2))
print(v2.dot(v1))

# Turns out that the dot product is commutative.

# Obligatory test for unequal vector lengths
v5.dot(v6) # Passed

[1, 2, 3]
[10, 20, 30]
140
140
[-1, -2, -3]
-140
-140


Exception: Vector of length 3 required to obtain the dot product. Provided vector is of length 4

**Verifying the above cases with Numpy**

In [98]:
print(n1.dot(n2))
n4 = np.array([-1, -2, -3])
print(n2.dot(n4))
print(n1.dot(n3))

140
-140


ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

### Task 1.a.iv Cross product of vectors  
My understanding about the cross product of 2 vectors:  
- Cross product results in a resultant vector.
- The resultant vector is perpendicular to the plane of the two vectors for whom the cross product is determined.
- The magnitude of the resultant vector is equal to the area of the parallelogram that the original two vecotors would form with each other.

#### Mathematical formula to compute a cross product:  
If there exists two vectors a = [ax, ay, az] and b = [bx, by, bz], then the cross product a X b can be computed as follows:  
    a X b = [aybz - azby, -(axbz - azbx), axby - aybx]  
 => a X b = [aybz - azby, azbx - axbz, axby - aybx]

In [99]:
# Function to compute and return the resultant Vector object from the corss product of two vectors.
def cross(self, vector: Vector) -> Vector:
    if self.checkIfEqualSize(vector) and vector.len == 3:
        abx = self.v[1]*vector.v[2] - self.v[2]*vector.v[1]
        aby = self.v[2]*vector.v[0] - self.v[0]*vector.v[2]
        abz = self.v[0]*vector.v[1] - self.v[1]*vector.v[0]
        return Vector([abx, aby, abz])
    else:
        raise Exception(f'Vector of 3 dimensions required.')

# Adding the above cross method to the Vector class
Vector.cross = cross

In [100]:
# Test cases
# Case 1
print(f'Vector v5: {v5}')
print(f'Vector v2: {v2}')
print(f'v5 X v2 = {v5.cross(v2)}')
# Case 2
v6 = Vector([2,3,4])
print(f'Vector v6: {v6}')
v7 = Vector([5,6,7])
print(f'Vector v7: {v7}')
print(f'v6 X v7 = {v6.cross(v7)}')
print(f'v7 X v6 = {v7.cross(v6)}') # changing order of cross product flips the direction of the resultant vector. 

# Verification with numpy
print('\nVerification with numpy')
print(n1, n2)
print(np.cross(n1, n2))
print(np.cross(np.array([1,2,3]), np.array([4,5,6])))

Vector v5: [1, 2, 3]
Vector v2: [10, 20, 30]
v5 X v2 = [0, 0, 0]
Vector v6: [2, 3, 4]
Vector v7: [5, 6, 7]
v6 X v7 = [-3, 6, -3]
v7 X v6 = [3, -6, 3]

Verification with numpy
[1 2 3] [10 20 30]
[0 0 0]
[-3  6 -3]


### b. Matrices  
Part 2 of the 1st activity extends the concept of the vector and introduces us to matrices. I shall also build a Matrix class that defines each row (i.e, sub-list) as a Vector object so that it can accommodate extra complexity that comes with a higher dimensionality.

In [154]:
class Matrix:

    # Constructor that calls the inherited constructor but also sets the shape for the matrix
    def __init__(self, mat: list):
        # Not a very elegant way in python for constructor overloading as it is not a statically typed language. :(
        if isinstance(mat, List) and isinstance(mat[0], Vector):
            self.mat = mat
        elif isinstance(mat, List) and isinstance(mat[0], List):
            self.mat = []
            for i in range(len(mat)):
                '''
                Initialising every row in the matrix to be a Vector object so that I can apply previously implemented methods directly.
                Note to self: I should be checking if each of the sub lists are of the same length. But, that seems like 
                I'm digressing too much.
                '''
                self.mat.append(Vector(mat[i]))
        else:
            raise Exception("Wrong input provided for the Matrix object.")
        self.shape = (len(self.mat), self.mat[0].len)

    # Defining the string representation for the Matrix object which is to be used when printed.
    def __str__(self):
        matStr = "["
        for row in self.mat:
            matStr += row.__str__() + "\n"
        matStr = matStr[:len(matStr)-1]
        matStr += "]"
        return matStr

In [155]:
# Util function to check if a Matrix object has the same shape as the current Matrix object
def isCompatibleShape(self, mat: Matrix) -> bool:
    return self.shape == mat.shape

# Adding the above util function to the Matrix class
Matrix.isCompatibleShape = isCompatibleShape

### Task 1.b.i Size (shape) of Matrix object

Every Matrix object is assigned a shape attribute on creation via the constructor. So, to find the shape of a matrix object, you can simply access it by calling the shape attribute.

In [156]:
# Test case 1
m1 = Matrix([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(f'Matrix m1:\n{m1}')
print(f'Shape of m1:{m1.shape}')

# Test case 2
m2 = Matrix([[1,2],
            [4,5],
            [7,8]])
print(f'Matrix m2:\n{m2}')
print(f'Shape of m1:{m2.shape}')

Matrix m1:
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
Shape of m1:(3, 3)
Matrix m2:
[[1, 2]
[4, 5]
[7, 8]]
Shape of m1:(3, 2)


### Task 1.b.ii Sum/subtract two matrices

Matrices of the same dimensions can be added or subtracted simply by directly performing the respective arithmetic operation between the positionally corresponding element in the matrices.

**Example:**  
```
A = [1, 2]  ,  B = [5, 6]  
    [3, 4]         [7, 8]

A + B = [1+5, 2+6] = [6,  8 ]
        [3+7, 4+8]   [10, 12]
```

In [162]:
# Function to add to matrices
def matAdd(self, mat: Matrix) -> Matrix:
    if self.isCompatibleShape(mat):
        matSum = []
        for i in range(self.shape[0]): # iterating through all the rows in the matrix
            '''
            Since all rows (sub-lists) in a Matrix object are essentially Vector objects, we can just directly call the add method
            of the previously defined Vector class. 
            Ref: cell under Task 1.a.ii Addition and subtraction of vectors
            '''
            matSum.append(self.mat[i].add(mat.mat[i]))
        return Matrix(matSum)
    else:
        raise Exception(f'Provided matrix is not of compatible shape. Required shape: {self.shape}')

def matSub(self, mat: Matrix) -> Matrix:
    if self.isCompatibleShape(mat):
        matDiff = []
        for i in range(self.shape[0]): # iterating through all the rows in the matrix
            # Same logic as in the above matAdd method. Reuse Vector code! :D
            matDiff.append(self.mat[i].subtract(mat.mat[i]))
        return Matrix(matDiff)
    else:
        raise Exception(f'Provided matrix is not of compatible shape. Required shape: {self.shape}')

Matrix.add = matAdd
Matrix.sub = matSub

In [166]:
# Test case 1 (Addition)
print(f'Matrix m1: \n{m1}')
m3 = Matrix([[1,2,3],
            [4,5,6],
            [7,8,9]])
m4 = m1.add(m3)
print(f'Sum of matrices m1 & m3: \n{m4}')

# Test case 2 (Subtraction)
m5 = m1.sub(m3)
print(f'Difference of matrices m1 & m3: \n{m5}')

#Test case 3 (Some thing other than a square matrix)
print(f'matrix m2: \n{m2}')
m6 = Matrix([[2,3],
           [-5,6],
           [8,-9]])
print(f'Sum of matrices m2 & m6: \n{m2.add(m6)}')

# Test case 4 (Using matrices of different shapes)
m6.sub(m5) # Exception thrown below. Passed!

Matrix m1: 
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
Sum of matrices m1 & m3: 
[[2, 4, 6]
[8, 10, 12]
[14, 16, 18]]
Difference of matrices m1 & m3: 
[[0, 0, 0]
[0, 0, 0]
[0, 0, 0]]
matrix m2: 
[[1, 2]
[4, 5]
[7, 8]]
Sum of matrices m2 & m6: 
[[3, 5]
[-1, 11]
[15, -1]]


Exception: Provided matrix is not of compatible shape. Required shape: (3, 2)

**Verifying the above cases with Numpy**

In [170]:
nm1 = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
nm2 = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(nm1+nm2)
print(nm1-nm2)
nm5 = np.array([[1,2],
            [4,5],
            [7,8]])
nm1-nm5

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

### Task 1.b.iii Multiplying a matrix with a vector
This is basically getting the Dot product between each row in the matrix and the vector. This is also why we need to ensure that the **size of** the **vector** is **equal** to the **number of columns** in the **matrix**.

In [194]:
# Function that takes a Vector object and multiplies it with its defined Matrix values
def matMulVec(self, vector: Vector) -> Vector:
    newVec = []
    if vector.len == self.shape[1]: # Ensuring that the vector length matches with the no. of columns in the matrix
        for row in self.mat:
            newVec.append(row.dot(vector))
        return Vector(newVec)
    else:
        raise Exception(f'Vector of size {self.shape[1]} expected while provided vector is of size {vector.len}')
    '''
    Figured since the exception is already handled in the dot() method in the Vector class, I don't need to explicity handle the 
    case with incompatible matrix and vector sizes here. But I'm doing it anyway:D
    '''
# Adding the above method to the Matrix class
Matrix.matMulVec = matMulVec

In [199]:
# Test case 1
print(f'Vector v2: \n{v2}')
print(f'Matrix m1: \n{m1}')
print(f'm1 * v2: \n{m1.matMulVec(v2)}')
print()
# Test case 2
m7 = Matrix([[1, -1, 2],
             [0, -3, 1]])
v8 = Vector([2, 1, 0])
print(f'm7 * v8: \n{m7.matMulVec(v8)}')
print()
#Test case 3 (Checking with incompatible matrix and vector sizes)
v9 = Vector([2, 1])
m7.matMulVec(v9) # passed!

Vector v2: 
[10, 20, 30]
Matrix m1: 
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
m1 * v2: 
[140, 320, 500]

m7 * v8: 
[1, -3]



Exception: Vector of size 3 expected while provided vector is of size 2

**Verifying the above cases with Numpy**

In [203]:
print(n2)
print(nm1)
print(np.matmul(nm1, n2))
print()
nm6 = np.array([[1, -1, 2],
                [0, -3, 1]])
n4 = np.array([2, 1, 0])
print(np.matmul(nm6, n4))
print()
# print(np.matmul(n4, nm6)) # This failed as well as the vector size no longer matched the no. of matrix columns when order was swapped.
print(np.matmul(nm6, np.array([2, 1])))

[10 20 30]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[140 320 500]

[ 1 -3]



ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Task 1.b.iv Multiplying a matrix with another matrix


In [ ]:
# Method to multiply two matrices
def matMulMat(self, mat: Matrix) -> Matrix:
    

## Discussion

Provide any discussion elements