### Your details

Name: **Siddharth Prince**

ID number: **23052058**

# Task 1

## Code

### House keeping code which includes any imports, general variable declarations, etc

In [1]:
# Imports
import numpy as np
from typing import List

### Note

The first code cell below contains all class code and util functions that would be useful in the context of a vector object. All the functions that implement the solutions to the given problems shall be provided in their own cells after the below code cell. This is my attempt at presenting my code in more readable chunks instead of a single class block with all the code in it.

## a. Vectors

In [2]:
# Defining a vector class so that it becomes more intuitive and straightforward to use these as objects and reduce code repetition.
# Working with Java for 3 years in industry has changed me as a programmer. :)
class Vector:
    # Initialising a Vector object with a list of numbers provided.
    def __init__(self, v: List):
        self.v = v
        self.len = len(v)

    # Defining the string representation of the object for print(). 
    # I did notice that numpy prints all elements without the comma, but that just seems cosmetic here.
    def __str__(self):
        return str(self.v)

    # Util function to set all values of the vector.
    def setVector(self, v: List):
        self.v = v
        

In [3]:
# Util function that checks if the passed Vector object has the same length as the current Vector object.
def checkIfEqualSize(self, v: Vector):
    return self.len == v.len

# adding above util function to the Vector class. 
# Had to add this in a separate code cell as I needed to check the passed parameter by type Vector.
Vector.checkIfEqualSize = checkIfEqualSize

## Task 1.a.i Scalar multiplication of vectors  
Scalar multiplication or "scaling" a vector as intuitively explained by 3B1B, is multiplying all components of a vector (usually the x, y and z components which represents it in 3d space) by a constant factor.  

## Approach

In my below implementation of the function to scale a vector, I have added the function "scaleVector" to the Vector class. The only parameter that is required is the scalar value. This function multiplies each element in the vector object with the scalar value. This operation is done in place.

In [4]:
# Function to scale a vector. This function changes the vector values in place.
def scaleVector(self, scalar: float):
    self.v = [scalar*i for i in self.v]

# adding the above function to the Vector class
Vector.scale = scaleVector

In [5]:
# Test cases
v1 = Vector([1,2,3])
print('Scaling v1 by a factor of 2:')
v1.scale(2)
print(f"New scaled vector: {v1}")
print('Scaling v1 by a factor of -0.5:')
v1.scale(-0.5)
print(f"New scaled vector: {v1}")
print('Setting new values to v1:')
v1.setVector([1,2,3]) # testing the setVector util function where it will change an existing vector to the new values provided
v2 = Vector([14012, -52, 332.1])
print('Scaling v2 by a factor of 2:')
v2.scale(2)
print(f"New scaled vector: {v2}")
# v3 = Vector([1])
# v3.scale(69)

Scaling v1 by a factor of 2:
New scaled vector: [2, 4, 6]
Scaling v1 by a factor of -0.5:
New scaled vector: [-1.0, -2.0, -3.0]
Setting new values to v1:
Scaling v2 by a factor of 2:
New scaled vector: [28024, -104, 664.2]


**Verifying the above cases with Numpy**

In [6]:
# Verifying with Numpy

n1 = np.array([1,2,3])
print('Scaling n1 by a factor of 2:')
n2 = 2*n1
print(n2)
print('Scaling n1 by a factor of -0.5:')
print(-0.5*n2)

Scaling n1 by a factor of 2:
[2 4 6]
Scaling n1 by a factor of -0.5:
[-1. -2. -3.]


## Task 1.a.ii Addition and subtraction of vectors  
Vector arithmetic as in the addition and subtraction is fairly straightforward. Each corresponding element in both vectors are added/subracted and the resulting values form the new vector.

**Example:**
```
A = [1, 2, 3]  ,  B = [4, 5, 6]
A + B = [1+4, 2+5, 3+6]
      = [5, 7, 9]
```


In [7]:
# Function for vector addition. This does not perform addition in place to the vector object.
def add(self, vector: Vector) -> Vector:
    if self.checkIfEqualSize(vector):
        return Vector([self.v[i] + vector.v[i] for i in range(self.len)])
    else:
        raise Exception(f'Vector of length {self.len} required to perform vector addition. Provided vector is of length {vector.len}')
        

# Function for vector addition. This does not perform addition in place to the vector object.
def subtract(self, vector: Vector) -> Vector:
    if self.checkIfEqualSize(vector):
        return Vector([self.v[i] - vector.v[i] for i in range(self.len)])
    else:
        raise Exception(f'Vector of length {self.len} required to perform vector subtraction. Provided vector is of length {vector.len}')

# adding the above functions to the Vector class
Vector.add = add
Vector.subtract = subtract

In [8]:
# Sum of vectors
print("Sum of vectors")
# Test cases
print(f'Vector v1: {v1}')
v2.setVector([10, 20, 30])
print(f'Vector v2: {v2}')
v3 = v1.add(v2)
print('Adding v1 & v2:')
print(v3)
print()
v1.setVector([-1, -2, -3])
print()
print(v1.add(v2))

# Subtraction of vectors
print("\nSubtraction of vectors")
# Test cases
v4 = v1.subtract(v2)
print(v4)
print()
v5 = v3.subtract(v2)
print(v5)

# Testing for Vectors with unequal lengths. The following cases should fail with an exception and appropriate message.
v6 = Vector([1,2,3,4])
# v5.add(v6) # Passed
v5.subtract(v6) # Passed

Sum of vectors
Vector v1: [1, 2, 3]
Vector v2: [10, 20, 30]
Adding v1 & v2:
[11, 22, 33]


[9, 18, 27]

Subtraction of vectors
[-11, -22, -33]

[1, 2, 3]


Exception: Vector of length 3 required to perform vector subtraction. Provided vector is of length 4

**Verifying the above cases with Numpy**

In [9]:
n2 = np.array([10,20,30])
print(n1 + n2)
print(n1 - n2)
n3 = np.array([1,2,3,4])
# n1 + n3 # testing for vector arithmetic operations of unequal size
n3 - n1 # Throws a more generic error message which has its merits for only having to maintain a single method, but... Sid's implementation - 1, Numpy - 0 XD

[11 22 33]
[ -9 -18 -27]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## Task 1.a.iii Dot product of vectors  
Dot product of vectors, from my understanding, is the sum of all corresponding products of elements of two equal length vectors. The resulting value is a scalar value. 
**Example:**  
```
A = [1, 2, 3]  ,  B = [4, 5, 6]
A + B = [1*4 + 2*5 + 3*6]
      = 32
```

## Approach
The below 'dot' method takes one argument of type Vector and returns the scalar dot product value.

In [10]:
# Function to compute the dot product of two vectors.
def dot(self, vector: Vector):
    # Checking that both Vector objects are of the same length.
    if self.checkIfEqualSize(vector):
        dotProduct = 0
        productList = [self.v[i] * vector.v[i] for i in range(self.len)]
        for number in productList:
            dotProduct += number
        return dotProduct
    else:
        raise Exception(f'Vector of length {self.len} required to obtain the dot product. Provided vector is of length {vector.len}')

# Adding the dot function to the Vector class
Vector.dot = dot

In [11]:
print(f'Vector v5: {v5}')
print(f'Vector v2: {v2}')
# Test case 1
print(f'v5.v2: {v5.dot(v2)}')
# Test case 2
print(f'v2.v5: {v2.dot(v5)}')

# Testing with a vector having negative elements in it
print(f'Vector v1: {v1}')
# Test case 3
print(f'v1.v2: {v1.dot(v2)}')
# Test case 4
print(f'v2.v1: {v2.dot(v1)}')

# Turns out that the dot product is commutative.

# Obligatory test for unequal vector lengths
# Test case 5
v5.dot(v6) # Passed

Vector v5: [1, 2, 3]
Vector v2: [10, 20, 30]
v5.v2: 140
v2.v5: 140
Vector v1: [-1, -2, -3]
v1.v2: -140
v2.v1: -140


Exception: Vector of length 3 required to obtain the dot product. Provided vector is of length 4

**Verifying the above cases with Numpy**

In [12]:
print(n1.dot(n2))
n4 = np.array([-1, -2, -3])
print(n2.dot(n4))
print(n1.dot(n3))

140
-140


ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

## Discussion
Since the vector dot product is a sum of products, both of which are individually commutative arithmetic operations, the dot product is also commutative. This is also evident from test cases #2 & #4.

## Task 1.a.iv Cross product of vectors  
My understanding about the cross product of 2 vectors:  
- Cross product results in a resultant vector.
- The resultant vector is perpendicular to the plane of the two vectors for whom the cross product is determined.
- The magnitude of the resultant vector is equal to the area of the parallelogram that the original two vecotors would form with each other.

### Mathematical formula to compute a cross product:  
If there exists two vectors A = [ax, ay, az] and B = [bx, by, bz], then the cross product a X b can be computed as follows:  
```
    A X B = [aybz - azby, -(axbz - azbx), axby - aybx]  
          = [aybz - azby, azbx - axbz, axby - aybx]
```

## Approach
I have directly taken the above formula and implemented in the below function by using the list indices.

In [13]:
# Function to compute and return the resultant Vector object from the corss product of two vectors.
def cross(self, vector: Vector) -> Vector:
    if self.checkIfEqualSize(vector) and vector.len == 3:
        abx = self.v[1]*vector.v[2] - self.v[2]*vector.v[1]
        aby = self.v[2]*vector.v[0] - self.v[0]*vector.v[2]
        abz = self.v[0]*vector.v[1] - self.v[1]*vector.v[0]
        return Vector([abx, aby, abz])
    else:
        raise Exception(f'Vector of 3 dimensions required.')

# Adding the above cross method to the Vector class
Vector.cross = cross

In [14]:
# Test cases
# Case 1
print(f'Vector v5: {v5}')
print(f'Vector v2: {v2}')
print(f'v5 X v2 = {v5.cross(v2)}')
# Case 2
v6 = Vector([2,3,4])
print(f'Vector v6: {v6}')
v7 = Vector([5,6,7])
print(f'Vector v7: {v7}')
print(f'v6 X v7 = {v6.cross(v7)}')
# Case 3
print(f'v7 X v6 = {v7.cross(v6)}') # changing order of cross product flips the direction of the resultant vector. 

# Verification with numpy
print('\nVerification with numpy')
print(n1, n2)
print(np.cross(n1, n2))
print(np.cross(np.array([1,2,3]), np.array([4,5,6]))) # <--
print(np.cross(np.array([2,3,4]), np.array([5,6,7]))) # <--
print(np.cross(np.array([211,212,213]), np.array([214,215,216]))) # <--
print(np.cross(2*np.array([1,2,3]), 2*np.array([4,5,6])))

Vector v5: [1, 2, 3]
Vector v2: [10, 20, 30]
v5 X v2 = [0, 0, 0]
Vector v6: [2, 3, 4]
Vector v7: [5, 6, 7]
v6 X v7 = [-3, 6, -3]
v7 X v6 = [3, -6, 3]

Verification with numpy
[1 2 3] [10 20 30]
[0 0 0]
[-3  6 -3]
[-3  6 -3]
[-3  6 -3]
[-12  24 -12]


## Discussion

There are 3 interesting observations I've made:  
- Flipping the order of two vectors in the cross muliplication results in the elements being negated which in effect means that the resultant vector's direction is flipped (thanks 3B1B :D).
-  The resultant vector's values don't change as long as the vectors follow the same pattern? **(See the lines in test code cell above commented with "<--" and its corresponding output via numpy).** The inference here is that this has little to do with the cross product but more to do with the nature of vectors themselves.
    - The vectors can always be added to and subtracted from to get the vector in the original position.
    - So, the positioning of the vectors do not affect the resultant vector from a cross product as long as the area of the parallelogram formed between them stay the same (3B1B ftw!).
-  The vector cross product scales with the same scalar factor with which the component vectors were scaled.

## b. Matrices  
Part 2 of the 1st activity extends the concept of the vector and introduces us to matrices. I shall also create a Matrix class that defines each row (i.e, sub-list) as a Vector object so that it can build upon the work done with the Vector class above.

In [15]:
class Matrix:

    # Constructor that calls the inherited constructor but also sets the shape for the matrix
    def __init__(self, mat: list):
        # Not a very elegant way in python for constructor overloading as it is not a statically typed language. :(
        if isinstance(mat, List) and isinstance(mat[0], Vector):
            self.mat = mat
        elif isinstance(mat, List) and isinstance(mat[0], List):
            self.mat = []
            for i in range(len(mat)):
                '''
                Initialising every row in the matrix to be a Vector object so that I can apply previously implemented methods directly.
                Note to self: I should be checking if each of the sub lists are of the same length. But, that seems like 
                I'm digressing too much.
                '''
                self.mat.append(Vector(mat[i]))
        else:
            raise Exception("Wrong input provided for the Matrix object.")
        self.shape = (len(self.mat), self.mat[0].len)

    # Defining the string representation for the Matrix object which is to be used when printed.
    def __str__(self):
        matStr = "["
        for row in self.mat:
            matStr += row.__str__() + "\n"
        matStr = matStr[:len(matStr)-1]
        matStr += "]"
        return matStr

In [16]:
# Util function to check if a Matrix object has the same shape as the current Matrix object
def isCompatibleShape(self, mat: Matrix) -> bool:
    return self.shape == mat.shape

# Util function to return a transposed version of the current matrix. Returns a new Matrix object and hence doesn't change in place.
def transpose(self):
    return Matrix([[self.mat[j].v[i] for j in range(self.shape[0])] for i in range(self.shape[1])])

# Adding the above util function to the Matrix class
Matrix.isCompatibleShape = isCompatibleShape
Matrix.transpose = transpose

### Task 1.b.i Size (shape) of Matrix object

Every Matrix object is assigned a shape attribute on creation via the constructor. So, to find the shape of a matrix object, you can simply access it by calling the shape attribute.

In [17]:
# Test case 1
m1 = Matrix([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(f'Matrix m1:\n{m1}')
print(f'Shape of m1:{m1.shape}')

# Test case 2
m2 = Matrix([[1,2],
            [4,5],
            [7,8]])
print(f'Matrix m2:\n{m2}')
print(f'Shape of m1:{m2.shape}')

Matrix m1:
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
Shape of m1:(3, 3)
Matrix m2:
[[1, 2]
[4, 5]
[7, 8]]
Shape of m1:(3, 2)


### Task 1.b.ii Sum/subtract two matrices

Matrices of the same dimensions can be added or subtracted simply by directly performing the respective arithmetic operation between the positionally corresponding element in the matrices.

**Example:**  
```
A = [1, 2]  ,  B = [5, 6]  
    [3, 4]         [7, 8]

A + B = [1+5, 2+6] = [6,  8 ]
        [3+7, 4+8]   [10, 12]
```

In [18]:
# Function to add to matrices
def matAdd(self, mat: Matrix) -> Matrix:
    if self.isCompatibleShape(mat):
        matSum = []
        for i in range(self.shape[0]): # iterating through all the rows in the matrix
            '''
            Since all rows (sub-lists) in a Matrix object are essentially Vector objects, we can just directly call the add method
            of the previously defined Vector class. 
            Ref: cell under Task 1.a.ii Addition and subtraction of vectors
            '''
            matSum.append(self.mat[i].add(mat.mat[i]))
        return Matrix(matSum)
    else:
        raise Exception(f'Provided matrix is not of compatible shape. Required shape: {self.shape}')

def matSub(self, mat: Matrix) -> Matrix:
    if self.isCompatibleShape(mat):
        matDiff = []
        for i in range(self.shape[0]): # iterating through all the rows in the matrix
            # Same logic as in the above matAdd method. Reuse Vector code! :D
            matDiff.append(self.mat[i].subtract(mat.mat[i]))
        return Matrix(matDiff)
    else:
        raise Exception(f'Provided matrix is not of compatible shape. Required shape: {self.shape}')

Matrix.add = matAdd
Matrix.sub = matSub

In [19]:
# Test case 1 (Addition)
print(f'Matrix m1: \n{m1}')
m3 = Matrix([[9,8,7],
            [6,5,4],
            [3,2,1]])
m4 = m1.add(m3)
print(f'Sum of matrices m1 & m3: \n{m4}')

# Test case 2 (Subtraction)
m5 = m1.sub(m3)
print(f'Difference of matrices m1 & m3: \n{m5}')

#Test case 3 (Some thing other than a square matrix)
print(f'matrix m2: \n{m2}')
m6 = Matrix([[2,3],
           [-5,6],
           [8,-9]])
print(f'Sum of matrices m2 & m6: \n{m2.add(m6)}')

# Test case 4 (Using matrices of different shapes)
m6.sub(m5) # Exception thrown below. Passed!

Matrix m1: 
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
Sum of matrices m1 & m3: 
[[10, 10, 10]
[10, 10, 10]
[10, 10, 10]]
Difference of matrices m1 & m3: 
[[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]]
matrix m2: 
[[1, 2]
[4, 5]
[7, 8]]
Sum of matrices m2 & m6: 
[[3, 5]
[-1, 11]
[15, -1]]


Exception: Provided matrix is not of compatible shape. Required shape: (3, 2)

**Verifying the above cases with Numpy**

In [20]:
nm1 = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
nm2 = np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])
print(nm1+nm2)
print(nm1-nm2)
nm5 = np.array([[1,2],
            [4,5],
            [7,8]])
nm1-nm5

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

### Task 1.b.iii Multiplying a matrix with a vector
This is basically getting the Dot product between each row in the matrix and the vector. This is also why we need to ensure that the **size of** the **vector** is **equal** to the **number of columns** in the **matrix**.

In [21]:
# Function that takes a Vector object and multiplies it with its defined Matrix values
def matMulVec(self, vector: Vector) -> Vector:
    newVec = []
    if vector.len == self.shape[1]: # Ensuring that the vector length matches with the no. of columns in the matrix
        for row in self.mat:
            newVec.append(row.dot(vector))
        return Vector(newVec)
    else:
        raise Exception(f'Vector of size {self.shape[1]} expected while provided vector is of size {vector.len}')
    '''
    Figured since the exception is already handled in the dot() method in the Vector class, I don't need to explicity handle the 
    case with incompatible matrix and vector sizes here. But I'm doing it anyway :P
    '''
# Adding the above method to the Matrix class
Matrix.matMulVec = matMulVec

In [22]:
# Test case 1
print(f'Vector v2: \n{v2}')
print(f'Matrix m1: \n{m1}')
print(f'm1 * v2: \n{m1.matMulVec(v2)}')
print()
# Test case 2
m7 = Matrix([[1, -1, 2],
             [0, -3, 1]])
v8 = Vector([2, 1, 0])
print(f'm7 * v8: \n{m7.matMulVec(v8)}')
print()
#Test case 3 (Checking with incompatible matrix and vector sizes)
v9 = Vector([2, 1])
m7.matMulVec(v9) # passed!

Vector v2: 
[10, 20, 30]
Matrix m1: 
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
m1 * v2: 
[140, 320, 500]

m7 * v8: 
[1, -3]



Exception: Vector of size 3 expected while provided vector is of size 2

**Verifying the above cases with Numpy**

In [23]:
print(n2)
print(nm1)
print(np.matmul(nm1, n2))
print()
nm6 = np.array([[1, -1, 2],
                [0, -3, 1]])
n4 = np.array([2, 1, 0])
print(np.matmul(nm6, n4))
print()
# print(np.matmul(n4, nm6)) # This failed as well as the vector size no longer matched the no. of matrix columns when order was swapped.
print(np.matmul(nm6, np.array([2, 1])))

[10 20 30]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[140 320 500]

[ 1 -3]



ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Task 1.b.iv Multiplying a matrix with another matrix
Matrix - Matrix multiplication is essentially taking the vector - matrix multiplication forward. Instead of multiplying (dot product) just a column matrix over the rows of another matrix, we find the dot products of a collection of column matrices (which is a matrix) with the rows of another matrix.


In [24]:
# Method to multiply two matrices
def matMulMat(self, mat: Matrix) -> Matrix:
    # check if the number of columns in the current matrix is equal to the number of rows in the passed matrix
    if self.shape[1] == mat.shape[0]:
        prodMat = []
        for row in self.mat:
            # Transposing the passed matrix so that I can directly apply the vector dot product function for each row.
            prodRow = [row.dot(i) for i in mat.transpose().mat]
            prodMat.append(prodRow) # I could have used list comprehension for this outer loop as well, but this seems more readable to me.
        return Matrix(prodMat)
    else:
        raise Exception(f'shape {self.shape} is incompatible with provided matrix shape {mat.shape} for multiplication.')

Matrix.matMulMat = matMulMat

In [25]:
# Test case 1 - Multiplying two 3x3 matrices
print(f'Matrix m1: \n{m1}')
print(f'Matrix m5: \n{m5}')
print(f'm1 * m3: \n{m1.matMulMat(m5)}')
print()
# Test case 2 - Multipying matrices that are not square matrices
print(f'Matrix m2T: \n{m2.transpose()}')
print(f'Matrix m3: \n{m3}')
print(f'm2T * m3: \n{m2.transpose().matMulMat(m3)}')
print()
# Test case 3 - Multipying a column matrix with a matrix having a higher shape
m6 = Matrix([[1,2,3]])
print(f'Matrix m6: \n{m6}')
print(f'Matrix m1: \n{m1}')
print(f'm6 * m1: \n{m6.matMulMat(m1)}')
print()
# print(f'm1 * m6: \n{m1.matMulMat(m6)}')

# Test case 4 - Multipying matrices that do not have compatible shapes
print(f'Matrix m2: \n{m2}')
print(f'Matrix m3: \n{m3}')
print(f'm2 * m3: \n{m2.matMulMat(m3)}') # Passed! Exception thrown.

Matrix m1: 
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
Matrix m5: 
[[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]]
m1 * m3: 
[[0, 12, 24]
[-18, 12, 42]
[-36, 12, 60]]

Matrix m2T: 
[[1, 4, 7]
[2, 5, 8]]
Matrix m3: 
[[9, 8, 7]
[6, 5, 4]
[3, 2, 1]]
m2T * m3: 
[[54, 42, 30]
[72, 57, 42]]

Matrix m6: 
[[1, 2, 3]]
Matrix m1: 
[[1, 2, 3]
[4, 5, 6]
[7, 8, 9]]
m6 * m1: 
[[30, 36, 42]]

Matrix m2: 
[[1, 2]
[4, 5]
[7, 8]]
Matrix m3: 
[[9, 8, 7]
[6, 5, 4]
[3, 2, 1]]


Exception: shape (3, 2) is incompatible with provided matrix shape (3, 3) for multiplication.

**Verifying the above cases with Numpy**

In [26]:
# print(np.matmul(nm1, nm2))
nm7 = np.array([[-8, -6, -4],
                [-2, 0, 2],
                [4, 6, 8]])
print(np.matmul(nm1, nm7))
nm8 = np.array([[1, 4, 7],
                [2, 5, 8]])
print(np.matmul(nm8, nm2))
print(np.matmul(nm2, nm8))

[[  0  12  24]
 [-18  12  42]
 [-36  12  60]]
[[54 42 30]
 [72 57 42]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Discussion

The above matMulMat method will perform vector multiplication with a matrix as well (as evident from test case #3) if you pass a column matrix as a Matrix object. This is obvious but worth pointing out so that we drive home that a vector is just a special case of a matrix.

## Task 1.b.v Determinant

Determinant of matrices are only applicable to square matrices. For the scope of the this activity, as mentioned in the activity notes, we will be working with 2x2 matrices only.

## Approach  
Determining the determinant of a 2x2 matrix is fairly straightforward and the process is similar to finding the cross product of two 2D vectors. I have implemented the function below to compute the determinant of a 2x2 matrix and only a 2x2 matrix since the instructions clearly state to return an error message for matrices of any other shape.

**Formula:**  
```
 M  = [m11, m12]
      [m21, m22]

|M| = |m11, m12|
      |m21, m22|

    = m11*m22 - m21*m12
```

In [27]:
# Function to find the determinant of a 2x2 matrix
def det2(self):
    # Checking if the function was called on a 2x2 matrix object
    if self.shape == (2, 2):
        return self.mat[0].v[0]*self.mat[1].v[1] - self.mat[0].v[1]*self.mat[1].v[0]
    else:
        raise Exception("Function only applicable for 2x2 matrices.")

# Adding function to the Matrix class
Matrix.det2 = det2

In [28]:
# Test case 1
m8 = Matrix([[1, 2],
             [3, 4]])
print(f'|m8| = {m8.det2()}')
print()
# Test case 2
m9 = Matrix([[1, 0],
             [0, 1]])
print(f'|m9| = {m9.det2()}')
print()
# Test case 3
m10 = Matrix([[1, 3],
              [0, -1]])
print(f'|m10| = {m10.det2()}')
m1.det2()

|m8| = -2

|m9| = 1

|m10| = -1


Exception: Function only applicable for 2x2 matrices.

**Verifying the above cases with Numpy**

In [29]:
nm9 = np.array([[1, 2],
                [3, 4]])
print(np.linalg.det(nm9)) # Wierd that numpy produces an answer with such high precision when there seems to be no need.
nm10 = np.array([[1, 3],
                 [0, -1]])
print(np.linalg.det(nm10))

-2.0000000000000004
-1.0


## Task 1.b.vi Inverse of a matrix

A matrix say, 'A' has an inverse only when the product of the matrix and its inverse results in an identity matrix.  
  
Side note:  
An identity matrix is a square matrix which has its leading diagonal elements as 1 and the rest as 0. If you multiply a matrix by an identity matrix, you get the same original matrix.

Thus, A * Ai = I where A is a square matrix, Ai (no pun intended) is its inverse and I is the identity matrix.

## Approach  
For a 2x2 matrix, the inverse can be obtained via the following formula:
```
If A = [m11, m12]
     = [m21, m22]

then, Ai (i.e, A inverse) =  (1/|A|) * [ m22, -m12]
                                       [-m21,  m11]
```
  
The below function implements the above formula and uses the already defined determinant method above.
**Note:**  
If the determinant of the matrix evaluates to 0, 1/|A| becomes undefined. Hence, such matrices are non-invertible or singular.

In [30]:
# Function to find the inverse of a 2x2 matrix
def inv2(self):
    # Find the determinant first. If 0, return stating that the matrix is non-invertible.
    # Also, checking of the matrix shape will be handled in the det2 method. No further handling needed here.
    det = self.det2()
    if det == 0:
        print("The matrix is non-invertible.")
        return -1
    invMat = Matrix([[self.mat[1].v[1], -self.mat[0].v[1]],
                     [-self.mat[1].v[0], self.mat[0].v[0]]])

    for row in invMat.mat:
        row.scale(1/det) # Using the scale method of the vector class to multiply all the rows with 1/|A|
    return invMat

Matrix.inv2 = inv2        

In [31]:
# Test case 1
print(f'Matrix m8: \n{m8}')
m11 = m8.inv2()
print(f'Inverse of m8: \n{m11}')
# We can test if this is indeed the inverse by multiplying it with the original to see if it results in an identity 2x2 matrix.
print(f'Multiplying m8 and its inverse to check if it results in an identity matrix:')
print(f'm8 * m8i: \n{m8.matMulMat(m11)}') # Voila! It DOES result in an identity matrix! :)
print()

# Test case 2 (non-invertible matrix)
m12 = Matrix([[3, 4],
              [6, 8]])
print(f'Matrix m12: \n{m12}')
m13 = m12.inv2()
print(f'Inverse of m8: \n{m13}') # Prints -1 as an error code.

# Test case 3 (non 2x2 matrix)
m2.inv2() # Passed!

Matrix m8: 
[[1, 2]
[3, 4]]
Inverse of m8: 
[[-2.0, 1.0]
[1.5, -0.5]]
Multiplying m8 and its inverse to check if it results in an identity matrix:
m8 * m8i: 
[[1.0, 0.0]
[0.0, 1.0]]

Matrix m12: 
[[3, 4]
[6, 8]]
The matrix is non-invertible.
Inverse of m8: 
-1


Exception: Function only applicable for 2x2 matrices.

**Verifying the above cases with Numpy**

In [32]:
print(np.linalg.inv(nm9))
nm11 = np.array([[3, 4],
                [6, 8]])
print(np.linalg.inv(nm11))

[[-2.   1. ]
 [ 1.5 -0.5]]


LinAlgError: Singular matrix